server:
    port: 8085
spring:
    application:
        name: search-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root@123
        url: jdbc:mysql://127.0.0.1:3306/MovieTicketBooking
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true

    elasticsearch:
        rest:
            uris: http://localhost:9200


