
server:
    port: 8085
    servlet:
        context-path: /api/v1.0/moviebooking
spring:
    application:
        name: theatre-mgt-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root@123
        url: jdbc:mysql://127.0.0.1:3306/movie_booking_db
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
#    kafka:
#        consumer:
#            auto-offset-reset: earliest
#            bootstrap-servers: localhost:9092
#            group-id: movie
#            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#            properties:
#                spring:
#                    json:
#                        trusted:
#                            packages: '*'
#        topic:
#            name: add_new_movie
management:
    endpoint:
        health:
            show-details: always
        metrics:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
